### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [feathersjs/feathers-ios#5]
Hi,
It's will be great to add [Carthage](https://github.com/Carthage/Carthage) support

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://realm.io/news/swift-dependency-management-with-carthage/)
- [Carthage Tutorial: Getting Started](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started)
- [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)
- [Creating Cross-Platform Swift Frameworks for iOS, watchOS, and tvOS via Carthage and CocoaPods](http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/)

**Comment by thebarndog** [comment]
@TofPlay, sure thing. feathers-ios isn't close to being done yet but once it is, I'll be sure to add Carthage support.
