### ISSUE TITLE
I wrote swift 3.0 client for Socket.IO - please check it out

### ISSUE THREAD

**Issue by kanstantsin-bucha** [feathersjs/feathers-ios#6]
I found this repo not updated anymore. So since I writing my new project using Featherjs and Socket.io - used to write my own client on swift 3.0.

The client work pretty stable now. So there is more work on response parsing since Feathersjs responses have a lot of different formats.

https://github.com/truebucha/FeathersjsClientSwift

**Comment by marshallswain** [comment]
This looks pretty nice on the surface.  Not sure when I'll get a chance to try it out.  But it looks like a lot of work went in to making it.  Thank you!

**Comment by ekryski** [comment]
Wicked! I added it to https://docs.feathersjs.com/why/showcase.html a while back. Going to close this but yes @truebucha thank you for writing that! Hopefully we'll have some time to try it out soon. Possibly @startupthekid and @ruddfawcett would be interested in collabing.
