### ISSUE TITLE
Repository status

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-ios#8]
Hey @corymsmith and @startupthekid what is the status of this repository? Is it usable? If not, I'd be inclined of making it private since there hasn't been a lot of activity lately and we don't want to cause false hopes ;)

**Comment by corymsmith** [comment]
I'd say not usable at this point, @startupthekid had mentioned the other day that he has some thoughts in how to sort some of this out but I agree that maybe we should make it private in the interim

**Comment by thebarndog** [comment]
I say go for it, I already have a fork going. I can ping you all when it's ready

**Comment by daffl** [comment]
Perfect, I was just going to ask. I'll do that then and we'll revisit once there is more to work with.
